myblog/blog/urls.py
from django.urls import path
from . import views
app_name="pingtai"
urlpatterns = [
    path('',views.index,name="index"),
    # path('admin/',views.admin,name="admin"),#后台界面
    # path('cate/',views.cate),
    # path('delkeyword/',views.delkeyword), #删除关键字
    # path('delCate/',views.delCate), #删除关键字
    # path('editCate/',views.editCate), #修改分类
    path('zhuce/',views.zhuce,name="zhuce"), #注册
    path('loginEmail/<user>.html',views.loginEmail), #修改分类
    path('islogin/',views.islogin,name="islogin"), #登录
    path('loginout/',views.loginout,name="loginout"), #退出
    path('person/',views.person,name="person"), #个人主页
    path('editperson/',views.editperson,name="editperson"), #个人主页
    path('upload/',views.upload,name="upload"), #上传头像
    path('kaitong/',views.kaitong,name="kaitong"), #开通博客
    path('fangjia/',views.fangjia,name="fangjia"),
    path('result/',views.index,name="result"),
    path('user/',views.user,name="user"), # 逻辑回归
    path('search/',views.search,name="search"), # 搜索功能

]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("blog.urls")),
    path('captcha/',include("captcha.urls")),
    path('self/',include("self.urls")),
    path(r'^ckeditor/', include('ckeditor_uploader.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/self/urls.py
from django.urls import path
from . import views
app_name="self"
urlpatterns = [
    path('index/<name>/',views.index,name="index"),  #个人博客首页
    path('liuyan/',views.liuyan,name="liuyan"),  #留言
    path('listliuyan/',views.listliuyan,name="listliuyan"),  #查看留言
    path('delliuyan/',views.delliuyan,name="delliuyan"),  #查看留言
    path('lianjie/',views.lianjie,name="lianjie"),  #链接
    path('admin/',views.admin,name="admin"),  #后台管理页面
    path('cate/',views.cate,name="cate"),  #个人博客分类
    path('delCate/',views.delCate,name="delCate"),  # 删除分类
    path('editCate/',views.editCate,name="editCate"),  # 修改分类
    path('content/',views.content,name="content"),  # 添加文章
    path('listcontent/',views.listcontent,name="listcontent"),  # 添加文章
    path('delcontent/',views.delcontent,name="delcontent"),  # 删除文章
    path('editcontent/',views.editcontent,name="editcontent"),  # 修改文章
    path('NB/<testWords>/',views.NB,name="NB"),  # 朴素贝叶斯算法
    path('detail/<id>/', views.detail, name="detail"),  # 详情
    path('follow/', views.follow, name="follow"),  # 关注
    path('quxiaofollow/', views.quxiaofollow, name="quxiaofollow"),  # 取消关注


]

myblog/blog/models.py
from django.db import models
from db.ModelDateBase import BaseModels
from django.contrib.auth.models import User


from django.contrib.auth.models import AbstractUser


class Info(models.Model):
    u=models.OneToOneField(to=User,on_delete=models.CASCADE,verbose_name="用户名")
    is_email=models.BooleanField(default=False,verbose_name="邮箱是否验证")
    img=models.ImageField(upload_to="img/",verbose_name="头像")
    phone = models.CharField(max_length=11,verbose_name="电话")
    company = models.CharField(max_length=30,verbose_name="所在公司")
    job = models.CharField(max_length=20,verbose_name="所从事的职业")
    science = models.CharField(max_length=30,verbose_name="感兴趣的方面")
    reason = models.CharField(max_length=200,verbose_name="开通博客的理由")
    real_name = models.CharField(max_length=10,verbose_name="真实姓名")
    age = models.IntegerField(verbose_name="年龄")
    sex = models.IntegerField(verbose_name="性别",choices=(
        (0, "男"),
        (1, "女"),
    ), default=0)
    type = models.IntegerField(verbose_name="类别", choices=(
        (1, "普通用户"),
        (2, "高级用户"),
        (3, "普通管理员"),
    ), default=0)
    salary = models.IntegerField(verbose_name="月薪")
    isadv = models.IntegerField(default=0)

    class Meta:
        verbose_name = "个人信息"
        verbose_name_plural = '个人信息'

class Category(models.Model):
    name=models.CharField(max_length=20)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "网站种类"
        verbose_name_plural = '网站种类'

class KeyWord(models.Model):
    c=models.ForeignKey(to=Category,on_delete=models.CASCADE)
    name=models.CharField(max_length=20)
    def __str__(self):
        return self.name


class Case(models.Model):
    area = models.IntegerField()
    dist = models.IntegerField(choices=(
        (1, "朝阳区"),
        (2, "海淀区"),
        (3, "东城区"),
        (4, "西城区"),
        (5, "石景山"),
    ), default=1)
    shi = models.IntegerField()
    hall = models.IntegerField()
    floor = models.IntegerField(choices=(
        (1, "低层"),
        (2, "中层"),
        (3, "高层"),
    ), default=1)
    school= models.IntegerField(choices=(
        (1, "是"),
        (2, "否")
    ), default=1)
    subway = models.IntegerField(choices=(
        (1, "是"),
        (2, "否")
    ), default=2)
    price=models.IntegerField()

myblog/self/models.py
from django.db import models
from db.ModelDateBase import BaseModels
# Create your models here.
from blog.models import User,Category,KeyWord
from ckeditor_uploader.fields import RichTextUploadingField



class Usercategory(models.Model):
    u=models.ForeignKey(to=User,on_delete=models.CASCADE)
    name=models.CharField(max_length=20)
    def __str__(self):
        return self.name
class Follow(models.Model):
    follow = models.ForeignKey(to=User, related_name="follow_user",on_delete=models.CASCADE)
    fan = models.ForeignKey(to=User, related_name="fan_user",on_delete=models.CASCADE)
    def __str__(self):
        # return "follow:{},fan:{}".format(self.follow, self.fan)
        return format(self.follow)

class Content(BaseModels):
    a=models.ForeignKey(verbose_name="作者",to=User,on_delete=models.CASCADE)
    c=models.ForeignKey(verbose_name="网站分类",to=Category,on_delete=models.CASCADE)
    k=models.ForeignKey(verbose_name="关键字",to=KeyWord,on_delete=models.CASCADE)
    sc=models.ForeignKey(verbose_name="个人分类",to=Usercategory,on_delete=models.CASCADE)
    title=models.CharField(max_length=50)
    con=RichTextUploadingField(verbose_name='正文')  # 富文本编辑器
    theme=models.IntegerField(choices=(
        (1,"简约"),
        (2,"清新"),
        (3,"雅致"),
        (4,"唯美"),
    ),default=1)
    s=models.IntegerField(choices=(
        (1,"发布"),
        (2,"草稿")
    ),default=2)
    page_view=models.IntegerField(verbose_name="浏览量")
    class Meta:
        verbose_name = "发表文章"
        verbose_name_plural = '发表文章'
    def __str__(self):
        return self.title
class Liuyan(models.Model):
    a=models.ForeignKey(verbose_name="作者",to=User,on_delete=models.CASCADE)
    name=models.CharField(max_length=20)
    tel=models.IntegerField(max_length=20)
    eamil=models.EmailField(max_length=20)
    word=models.CharField(max_length=20)

myblog/self/views.py
from django.shortcuts import render,HttpResponse,reverse,redirect
import json
import re
import numpy as np
import jieba
from blog.models import *
from self.models import Usercategory,Liuyan,Content,Follow
from util.util import authuser,auth
from django.core import paginator
from self.form import LiuyanForm,ContentModelForm
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
# 个人博客主页
@authuser
def index(request,name):
    name = ""
    if request.user.is_authenticated:
        name = request.user.username
        id = User.objects.filter(username=name).first().id
        imgurl = Info.objects.filter(u_id=id).first().img
        type = Info.objects.filter(u_id=id).first().type
        if type==3:
            content = Content.objects.filter(a_id=id).all()
            print(content)
            return render(request,"self/index.html",{'name': name, 'img': imgurl,'content':content})
        else:
            return redirect(reverse("pingtai:kaitong"))
# 留言
@csrf_exempt
@authuser
def liuyan(request):
    message = {'type': '', 'nicheng': '','tel':'','eamil':'','word':'','count':''}
    name = request.user.username
    id = User.objects.filter(username=name).first().id
    imgurl = Info.objects.filter(u_id=id).first().img
    form = LiuyanForm(request.POST)
    liuyan=Liuyan.objects.all()

    count=liuyan.count()
    print("123456789")
    if request.method=='POST':
        print("liuyan")
        nicheng = request.POST.get('nicheng', None)
        tel = request.POST.get('tel', None)
        eamil = request.POST.get('eamil', None)
        word = request.POST.get('word', None)
        print(tel,word)
        predict=NB(request, word)
        print("predict",predict)
        if predict==0:
            Liuyan.objects.create(name=nicheng, tel=tel, eamil=eamil, word=word, a_id=id)
            message['type']="ok"
            message['nicheng']=nicheng
            message['tel']=tel
            message['eamil']=eamil
            message['word']=word
            message['count']=count
        else:
            print("恶意评论")
            message['type']="error"
        return HttpResponse(json.dumps(message))

    return render(request, "self/liuyan.html",{'name': name, 'img': imgurl,'form':form,'liuyan':liuyan,'count':count})
# 查看留言
def listliuyan(request):
    name = request.user.username
    a_id=User.objects.filter(username=name).first().id
    liuyan=Liuyan.objects.filter(a_id=a_id).all()

    # 使用Paginator方法返回一个分页的对象，这个对象包括所有数据，分页的情况
    pag = paginator.Paginator(liuyan, 3)

    page = request.GET.get('page',1)  # QueryDict objects,如果没有对应的page键，就返回默认1。
    page_info = pag.get_page(page)  # 根据索引page，返回该page页数据，如果不存在，引起 InvalidPage异常

    # 构造上下文，以便html文件中能调用对应页的数据

    return render(request, "self/listliuyan.html",{'liuyan':liuyan,'page_info':page_info})
# 删除留言
@csrf_exempt
def delliuyan(request):
    message = {'code': '', 'data': ''}
    if request.method == "POST":
        kid = request.POST.get('id', None)
        if kid:
            message['code'] = "ok"
            Liuyan.objects.filter(id=kid).delete()
            return HttpResponse(json.dumps(message))
    message['code'] = "error"
    return HttpResponse(json.dumps(message))

# 后台管理页面
@authuser
def admin(request):
    name=request.user.username
    id = User.objects.filter(username=name).first().id
    imgurl = Info.objects.filter(u_id=id).first().img
    return render(request,"self/admin.html",{'name': name, 'img': imgurl})
def cate(request):
    cate = Usercategory.objects.all()
    if request.method=="POST":

        name = request.user.username
        u_id=User.objects.filter(username=name).first().id
        title = request.POST.get('title', None)
        print(title)
        if title:
            Usercategory.objects.create(name=title, u_id=u_id)
    return render(request, "self/cate.html",{'cate':cate})
# def cate(request):
#     name = request.COOKIES.get("name", None)
#     name = json.loads(name)
#     u_id = User.objects.filter(username=name).first().id
#     cate=Usercategory.objects.filter(u_id=u_id)
#     if request.method == "POST":
#         form=Cate(request.POST)
#         print(dir(form))
#         if form.is_valid:
#             name=form.cleaned_data['name']
#             Usercategory.objects.create(name=name, u_id=u_id)
#             return render(request, "self/cate1.html", {'form': "",'cate': cate})
#         else:
#             return render(request, "self/cate1.html", {'form':form,'cate': cate,})
#
#     else:
#         form=Cate()
#     return render(request, "self/cate1.html",{'form':form,'cate': cate})


# 删除个人博客分类:
@csrf_exempt
def delCate(request):
    message={'code':'','data':''}
    if request.method=="POST":
        kid=request.POST.get('id',None)
        if kid:
            message['code'] = "ok"
            Usercategory.objects.filter(id=kid).delete()
            return HttpResponse(json.dumps(message))
    message['code']="error"
    return HttpResponse(json.dumps(message))
# 修改个人博客分类
@csrf_exempt
def editCate(request):
    message = {'code': '', 'data': ''}
    if request.method == "POST":
        kid = request.POST.get('id', None)
        name = request.POST.get('name', None)
        print(name)
        if kid and name:
            message['code'] = "ok"
            Usercategory.objects.filter(id=kid).update(name=name)
            return HttpResponse(json.dumps(message))
    message['code'] = "error"
    return HttpResponse(json.dumps(message))


@authuser
def content(request):

    name = request.user.username
    # form=""
    cate=Category.objects.all()
    if request.method=="GET":
        form=ContentModelForm()
    else:
       # 表单提交
       # 验证modelform  关键字 分类 手动验证
       # 出错
        form = ContentModelForm(request.POST)

        if form.is_valid():
            print("验证成功")
            #手动验证
            kw=request.POST.get('kw',None)
            print("kw",kw)
            if kw:
                length=len(KeyWord.objects.filter(id=kw))
                if length>0:
                    k=KeyWord.objects.filter(id=kw).first()
                    c=k.c

                    a = User.objects.filter(username=name).first()
                    data=form.cleaned_data
                    textWords=data['con']
                    NB(request,textWords)
                    Content.objects.create(**form.cleaned_data,k=k,c=c,a=a,page_view=0)
        else:
            pass
    return render(request,"self/addcon.html",{'form':form,'cate':cate})
# 查看博客文章
@authuser
def listcontent(request):

    name = request.user.username
    a_id = User.objects.filter(username=name).first().id
    content = Content.objects.filter(a_id=a_id).all()
    pag = paginator.Paginator(content, 3)
    # 使用此判断语句是为了在用户跳转www.xxx.com/info/时也能访问第一页

    # 返回指定（page）页的数据，用于呈现在指定页上
    page = request.GET.get('page', 1)  # QueryDict objects,如果没有对应的page键，就返回默认1。
    page_info = pag.get_page(page)  # 根据索引page，返回该page数据，如果不存在，引起 InvalidPage异常
    return render(request,"self/listcon.html",{'page_info':page_info})
# 删除博客文章
# 删除个人博客分类:
@csrf_exempt
def delcontent(request):
    message={'code':'','data':''}
    if request.method=="POST":
        kid=request.POST.get('id',None)
        if kid:
            message['code'] = "ok"
            Content.objects.filter(id=kid).delete()
            return HttpResponse(json.dumps(message))
    message['code']="error"
    return HttpResponse(json.dumps(message))
# 修改博客文章
@csrf_exempt
def editcontent(request):
    name = request.user.username
    cate=Category.objects.all()
    if request.method=="GET":
        form=ContentModelForm()
    else:
       # 表单提交
       # 验证modelform  关键字 分类 手动验证
       # 出错
        form = ContentModelForm(request.POST)
        id=request.POST.get('id',None)
        print("修改的id",id)
        if form.is_valid():
            #手动验证
            kw=request.POST.get('kw',None)
            print("kw",kw)
            if kw:
                length=len(KeyWord.objects.filter(id=kw))
                if length>0:
                    k=KeyWord.objects.filter(id=kw).first()
                    c=k.c

                    a = User.objects.filter(username=name).first()
                    data=form.cleaned_data
                    textWords=data['con']
                    NB(request,textWords)
                    Content.objects.filter(id=id).update(title=data['title'],con=data['con'],theme=int(data['theme']),s=int(data['s']),sc=int(data['sc']),k=k,c=c,a=a,page_view=0)
        else:
            pass
    return render(request,"self/editcon.html",{'form':form,'cate':cate})
# 详情页
def detail(request,id):
    con=Content.objects.filter(id=id)
    fan_id=request.user.id #登录的人点击别人的关注，也就是粉丝

    name=Content.objects.filter(id=id).first().a  #每一个详情页的作者，被关注者
    name_id=User.objects.filter(username=name).first().id

    follows=Follow.objects.filter(fan_id=fan_id).all()  #登录的人的所有关注者
    is_guanzhu=""
    for item in follows:
        print(item)
        follow_id=User.objects.filter(username=item).first().id
        print(follow_id)
        if name_id==follow_id:
            is_guanzhu=1
            break
        else:
            is_guanzhu=0
    try:
        img=Content.objects.filter(id=id).first().a.info.img
    except:
        img=None
    print("zuozhe",name)
    return render(request, "self/xiangqing.html",{'name':name,'con':con,'img':img,'is_guanzhu':is_guanzhu})
# 关注
@csrf_exempt
def follow(request):
    message={'result':''}
    if request.is_ajax:
        fan=request.user.id
        guanzhu=request.POST.get('guanzhu',None)
        print("粉丝",fan)
        print("被关注者",guanzhu)
        follow=User.objects.filter(username=guanzhu).first().id
        print(follow)
        Follow.objects.create(fan_id=fan,follow_id=follow)
        message['result']="ok"
        return HttpResponse(json.dumps(message))
# 取消关注
@csrf_exempt
def quxiaofollow(request):
    message = {'result': ''}
    if request.is_ajax:
        fan = request.user.id
        guanzhu = request.POST.get('guanzhu', None)

myblog/self/templates/self/admin.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
     <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="renderer" content="webkit">
    <title>平台管理中心</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'self/css/pintuer.css' %}">
    <link rel="stylesheet" href="{% static 'self/css/admin.css' %}">
    <script src="{% static 'pingtai/js/jquery.js' %}"></script>
</head>
<style>
    .leftnav-title{
        background-color:#586933;
    }
</style>
<body style="background-color:#f2f9fd;">
<div class="header bg-main">
  <div class="logo margin-big-left fadein-top">
    <h1>
      <img src="/media/{{ img }}" class="radius-circle rotate-hover" height="50" alt="" />管理中心
    </h1>
  </div>
  <div class="head-l">
    <a class="button button-little bg-green" style="background:#586933;border-color:#586933;" href="{% url 'self:index' name %}" target="_blank">
      <span class="icon-home"></span> 
      个人博客首页
    </a> &nbsp;&nbsp;
     <a class="button button-little bg-red" style="background:#A79C87;border-color:#A79C87;color:black;" href="{% url 'pingtai:loginout' %}"><span class="icon-power-off"></span> 退出登录</a> </div>
</div>
<div class="leftnav">
  <div class="leftnav-title"><strong><span class="icon-list"></span>菜单列表</strong></div>
  <h2><span class="icon-user"></span>分类管理</h2>
  <ul style="display:block">
    <li><a href="{% url 'self:cate' %}" target="right"><span class="icon-caret-right"></span>个人分类管理</a></li>
  </ul>
  <h2><span class="icon-pencil-square-o"></span>文章管理</h2>
  <ul>
    <li><a href="{% url 'self:listcontent' %}" target="right"><span class="icon-caret-right"></span>查看文章</a></li>
    <li><a href="{% url 'self:content' %}" target="right"><span class="icon-caret-right"></span>添加文章</a></li>
  </ul>
    <h2><span class="icon-pencil-square-o"></span>评论管理</h2>
  <ul>
    <li><a href="list.html" target="right"><span class="icon-caret-right"></span>查看评论</a></li>
  </ul>
    <h2><span class="icon-pencil-square-o"></span>链接</h2>
  <ul>
    <li><a href="list.html" target="right"><span class="icon-caret-right"></span>查看链接</a></li>
  </ul>
    <h2><span class="icon-pencil-square-o"></span>留言管理</h2>
  <ul>
    <li><a href="{% url 'self:listliuyan' %}" target="right"><span class="icon-caret-right"></span>查看留言</a></li>
  </ul>
    <h2><span class="icon-pencil-square-o"></span>个人中心</h2>
  <ul>
    <li><a href="{% url 'pingtai:person' %}" target="right"><span class="icon-caret-right"></span>查看信息</a></li>
  </ul>
</div>
<script type="text/javascript">
$(function(){
  $(".leftnav h2").click(function(){
	  $(this).next().slideToggle(200);	
	  $(this).toggleClass("on"); 
  })
  $(".leftnav ul li a").click(function(){
	    $("#a_leader_txt").text($(this).text());
  		$(".leftnav ul li a").removeClass("on");
		$(this).addClass("on");
  })
});
</script>
<ul class="bread">
  <li><a href="{:U('Index/info')}" target="right" class="icon-home"> 首页</a></li>
  <li><a href="##" id="a_leader_txt">网站信息</a></li>
  <li><b>当前语言：</b><span style="color:red;">中文</php></span>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;切换语言：<a href="##">中文</a> &nbsp;&nbsp;<a href="##">英文</a> </li>
</ul>
<div class="admin">
  <iframe scrolling="auto" rameborder="0" src="" name="right" width="100%" height="100%"></iframe>
</div>
<div style="text-align:center;">
</div>
</body>
</html>

myblog/self/templates/self/lianjie.html
{% extends 'self/muban.html'%}

{% block css%}
{% load static %}
<link rel="stylesheet" href="{% static '/self/css/lianjie.css' %}">
{% endblock%}

{% block main %}
    <main>
        <div class="con">
            <h1>我的关注</h1>
            <h2>Life Blog</h2>
            <h3>4 items in collection</h3>
            <ul>
                {% for item in follows %}
                <li>
                    {% if item.follow.info.img %}
                    <div class="pic" style="background: url({% static '/pingtai/{{ item.follow.info.img }}' %}}) no-repeat center;background-size:cover;"></div>
                    {% else %}
                     <div class="pic" style="background-image: url({% static '/pingtai/img/omikron.png' %});
                     background-repeat:no-repeat;background-position:center;background-size:contain;background-color:#586933;"></div>
                    {% endif %}
                    <div class="name">{{ item }}</div>
                </li>
                {% endfor %}

            </ul>
        </div>

    </main>
{% endblock %}

{% block js %}
<script src="{% static 'pingtai/js/index1.js' %}"></script>
{% endblock %}

myblog/self/templates/self/muban.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>首页</title>
    {% load static %}
    <script src="{% static '/pingtai/js/jquery.js' %}"></script>
    <link rel="stylesheet" href="https://at.alicdn.com/t/font_850328_4weqx76q6s5.css">
    {% block css%}
    {% endblock%}

</head>
<body>
<!--背景图片-->
    <div class="fixed"></div>
<!--菜单-->
    <ul class="meau">

        <li><a href="{% url 'pingtai:index' %}">首页</a></li>
        <li><a href="{% url 'self:index' name %}">个人首页</a></li>
        <li><a href="{% url 'pingtai:person' %}">链接</a></li>

        <li><a href="{% url 'self:liuyan' %}">我的留言</a></li>
        <li><a href="{% url 'self:admin' %}">管理</a></li>
    </ul>
<!--搜索页面开始-->
    <div class="alert">
        <div class="search">Type then select or enter</div>o
    </div>
<!--搜索页面结束-->
    <header>
        <div class="left">
            <i class="iconfont icon-sousuo"></i>
        </div>
        <div class="right" id="meau">
            <i class="iconfont icon-caidan"></i>
        </div>
    </header>
    <div class="head">
        <div class="center">
            {% if img %}
            <div class="top" style="background: url(/media/{{ img }}) no-repeat center;background-size:cover;"></div>
            {% else %}
            <div class="top" style="background: url({% static '/pingtai/img/omikron.png' %}) no-repeat center;background-size:contain;"></div>
            {% endif %}
            <h3 class="guanzhu">{{ name }} </h3>
            {% if is_guanzhu == 0 %}
            <span class="follow">关注</span>
            {% else %}
            <span class="quxiao_follow">已关注</span>
            {% endif %}
        </div>
    </div>
<!--顶部效果-->
    <div class="wrapper">
        <svg id="header-decor" class="decor bottom" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 100 100" preserveAspectRatio="none">
            <path class="large left" d="M0 0 L50 50 L0 100" fill="rgba(255,255,255, .1)"></path>
            <path class="large right" d="M100 0 L50 50 L100 100" fill="rgba(255,255,255, .1)"></path>
            <path class="medium left" d="M0 100 L50 50 L0 33.3" fill="rgba(255,255,255, .3)"></path>
            <path class="medium right" d="M100 100 L50 50 L100 33.3" fill="rgba(255,255,255, .3)"></path>
            <path class="small left" d="M0 100 L50 50 L0 66.6" fill="rgba(255,255,255, .5)"></path>
            <path class="small right" d="M100 100 L50 50 L100 66.6" fill="rgba(255,255,255, .5)"></path>
            <path d="M0 99.9 L50 49.9 L100 99.9 L0 99.9" fill="rgba(255,255,255, 1)"></path>
            <path d="M48 52 L50 49 L52 52 L48 52" fill="rgba(255,255,255, 1)"></path>
        </svg>
    </div>

<!--主要内容部分-->
    {% block main%}
    {% endblock%}

<!--底部效果-->
    <div class="wrapper wrapper1">
        <svg id="header-decor" class="decor bottom" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 100 100" preserveAspectRatio="none">
            <path class="large left" d="M0 0 L50 50 L0 100" fill="rgba(255,255,255, .1)"></path>
            <path class="large right" d="M100 0 L50 50 L100 100" fill="rgba(255,255,255, .1)"></path>
            <path class="medium left" d="M0 100 L50 50 L0 33.3" fill="rgba(255,255,255, .3)"></path>
            <path class="medium right" d="M100 100 L50 50 L100 33.3" fill="rgba(255,255,255, .3)"></path>
            <path class="small left" d="M0 100 L50 50 L0 66.6" fill="rgba(255,255,255, .5)"></path>
            <path class="small right" d="M100 100 L50 50 L100 66.6" fill="rgba(255,255,255, .5)"></path>
            <path d="M0 99.9 L50 49.9 L100 99.9 L0 99.9" fill="rgba(255,255,255, 1)"></path>
            <path d="M48 52 L50 49 L52 52 L48 52" fill="rgba(255,255,255, 1)"></path>
        </svg>
    </div>

<footer>
    <ul class="top">
        <li>
            <i class="iconfont icon-weibo"></i>
        </li>
        <li>
            <i class="iconfont icon-ai-weixin"></i>
        </li>
        <li>
            <i class="iconfont icon-qq"></i>
        </li>
    </ul>
    <div class="bottom">Copyright©2018. Design by 17sucai</div>
</footer>

</body>
{% block js%}
{% endblock%}
<script>
    $(".center").click(function(e){
        let target=$(e.target)
        let guanzhu=$('.guanzhu').text()
        console.log(guanzhu)
        console.log("关注")
        if(target.hasClass("follow")){
            $.ajax({
                url:"/self/follow/",
                type:'post',
                dataType:"json",
                data:{guanzhu:guanzhu},
                success:function(e){
                    if(e.result=='ok'){
                        console.log("关注成功")
                        target.replaceWith($(
                        `
                            <span class="quxiao_follow">已关注</span>
                        `
                        ))
                    }
                }
            })
        }
        if(target.hasClass("quxiao_follow")){
            let guanzhu=$('.guanzhu').text()
            console.log(guanzhu)
            console.log("取消关注")
            $.ajax({
                url:"/self/quxiaofollow/",
                type:'post',
                dataType:"json",
                data:{guanzhu:guanzhu},
                success:function(e){
                    if(e.result=='ok'){
                        console.log("取消关注成功")
                        target.replaceWith($(
                        `
                            <span class="follow">关注</span>
                        `
                        ))
                    }
                }
            })
        }


    })

</script>
</html>