myblog/blog/urls.py
from django.urls import path
from . import views
app_name="pingtai"
urlpatterns = [
    path('',views.index,name="index"),
    # path('admin/',views.admin,name="admin"),#后台界面
    # path('cate/',views.cate),
    # path('delkeyword/',views.delkeyword), #删除关键字
    # path('delCate/',views.delCate), #删除关键字
    # path('editCate/',views.editCate), #修改分类
    path('zhuce/',views.zhuce,name="zhuce"), #注册
    path('loginEmail/<user>.html',views.loginEmail), #修改分类
    path('islogin/',views.islogin,name="islogin"), #登录
    path('loginout/',views.loginout,name="loginout"), #退出
    path('person/',views.person,name="person"), #个人主页
    path('editperson/',views.editperson,name="editperson"), #个人主页
    path('upload/',views.upload,name="upload"), #上传头像
    path('kaitong/',views.kaitong,name="kaitong"), #开通博客
    path('fangjia/',views.fangjia,name="fangjia"),
    path('result/',views.index,name="result"),
    path('user/',views.user,name="user"), # 逻辑回归
    path('search/',views.search,name="search"), # 搜索功能

]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("blog.urls")),
    path('captcha/',include("captcha.urls")),
    path('self/',include("self.urls")),
    path(r'^ckeditor/', include('ckeditor_uploader.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/blog/models.py
from django.db import models
from db.ModelDateBase import BaseModels
from django.contrib.auth.models import User


from django.contrib.auth.models import AbstractUser


class Info(models.Model):
    u=models.OneToOneField(to=User,on_delete=models.CASCADE,verbose_name="用户名")
    is_email=models.BooleanField(default=False,verbose_name="邮箱是否验证")
    img=models.ImageField(upload_to="img/",verbose_name="头像")
    phone = models.CharField(max_length=11,verbose_name="电话")
    company = models.CharField(max_length=30,verbose_name="所在公司")
    job = models.CharField(max_length=20,verbose_name="所从事的职业")
    science = models.CharField(max_length=30,verbose_name="感兴趣的方面")
    reason = models.CharField(max_length=200,verbose_name="开通博客的理由")
    real_name = models.CharField(max_length=10,verbose_name="真实姓名")
    age = models.IntegerField(verbose_name="年龄")
    sex = models.IntegerField(verbose_name="性别",choices=(
        (0, "男"),
        (1, "女"),
    ), default=0)
    type = models.IntegerField(verbose_name="类别", choices=(
        (1, "普通用户"),
        (2, "高级用户"),
        (3, "普通管理员"),
    ), default=0)
    salary = models.IntegerField(verbose_name="月薪")
    isadv = models.IntegerField(default=0)

    class Meta:
        verbose_name = "个人信息"
        verbose_name_plural = '个人信息'

class Category(models.Model):
    name=models.CharField(max_length=20)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "网站种类"
        verbose_name_plural = '网站种类'

class KeyWord(models.Model):
    c=models.ForeignKey(to=Category,on_delete=models.CASCADE)
    name=models.CharField(max_length=20)
    def __str__(self):
        return self.name


class Case(models.Model):
    area = models.IntegerField()
    dist = models.IntegerField(choices=(
        (1, "朝阳区"),
        (2, "海淀区"),
        (3, "东城区"),
        (4, "西城区"),
        (5, "石景山"),
    ), default=1)
    shi = models.IntegerField()
    hall = models.IntegerField()
    floor = models.IntegerField(choices=(
        (1, "低层"),
        (2, "中层"),
        (3, "高层"),
    ), default=1)
    school= models.IntegerField(choices=(
        (1, "是"),
        (2, "否")
    ), default=1)
    subway = models.IntegerField(choices=(
        (1, "是"),
        (2, "否")
    ), default=2)
    price=models.IntegerField()

myblog/blog/views.py
from django.shortcuts import render,redirect,reverse

from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from self.models import Content

from django.contrib.auth import authenticate, login,logout


from util.util import *
def index(request):
    # if request.user.is_authenticated:
    name=request.user.username
    print("name:",name)
    category=Category.objects.all()
    content=Content.objects.all()
    try:
        id = User.objects.filter(username=name).first().id
        type=Info.objects.filter(u_id=id).first().type
        img = User.objects.filter(username=name).first().info.img
        isadv = Info.objects.filter(u_id=id).first().isadv
        print(img)
    except:
        type=None
        img=None
        isadv=None
    return render(request,"pingtai/shouye.html",{'name':name,'type':type,'isadv':isadv,'category':category,'content':content,'img':img})




def search(request):
    if request.method=="POST":
        name = request.user.username
        print("name:", name)
        category = Category.objects.all()
        content = Content.objects.all()
        id = User.objects.filter(username=name).first().id

        try:
            type = Info.objects.filter(u_id=id).first().type
            img = User.objects.filter(username=name).first().info.img
            isadv = Info.objects.filter(u_id=id).first().isadv
            print(img)
        except:
            type = None
            img = None
            isadv = None
        print("搜索")
        q = request.POST.get('sousuo',None)
        error_msg = ''

        if not q:
            error_msg = '请输入关键词 ！！'
            return render(request, "pingtai/shouye.html",
                          {'name': name, 'type': type, 'isadv': isadv, 'category': category, 'content': content,
                           'img': img, 'error_msg': error_msg})
        else:
            post_list = Content.objects.filter(title__icontains=q)
            print(post_list)

            return render(request, "pingtai/search.html",{'name':name,'type':type,'isadv':isadv,'category':category,'content':content,
                                                      'img':img,'error_msg': error_msg,'post_list': post_list})
    return redirect(reverse("pingtai:index"))



@auth
def admin(request):
    return render(request,"pingtai/admin.html")
def cate(request):
    cate = Category.objects.all()
    if request.method == "POST":
        type=request.POST.get('type',None)
        name = request.POST.get('name',None)
        tits = request.POST.get('tits',None)
        if type != "0":
            # 添加关键字
            if name:
                KeyWord.objects.create(name=name,c_id=int(type))
            if tits:
                arr = tits.split(",")
                for item in arr:
                    KeyWord.objects.create(name=item,c_id=int(type))
        else:
            #添加分类
            if name:
                Category.objects.create(name=name)
            if tits:
                arr=tits.split(",")
                for item in arr:
                    Category.objects.create(name=item)
    return render(request,"pingtai/cate.html",{'cate':cate})

# 删除关键字:
@csrf_exempt
def delkeyword(request):
    message={'code':'','data':''}
    if request.method=="POST":
        kid=request.POST.get('id',None)
        if kid:
            message['code'] = "ok"
            KeyWord.objects.filter(id=kid).delete()
            return HttpResponse(json.dumps(message))

    message['code']="error"
    return HttpResponse(json.dumps(message))
# 删除分类:
@csrf_exempt
def delCate(request):
    message={'code':'','data':''}
    if request.method=="POST":
        kid=request.POST.get('id',None)
        if kid:
            message['code'] = "ok"
            Category.objects.filter(id=kid).delete()
            return HttpResponse(json.dumps(message))
    message['code']="error"
    return HttpResponse(json.dumps(message))
# 修改分类
@csrf_exempt
def editCate(request):
    message = {'code': '', 'data': ''}
    if request.method == "POST":
        kid = request.POST.get('id', None)
        name = request.POST.get('name', None)
        print(name)
        if kid and name:
            message['code'] = "ok"
            Category.objects.filter(id=kid).update(name=name)
            return HttpResponse(json.dumps(message))
    message['code'] = "error"
    return HttpResponse(json.dumps(message))
# 注册
def zhuce(request):
    if request.method=="POST":
        form=Zhuce(request.POST)
        if form.is_valid():
            print("注册")
            data=form.cleaned_data
            newuser=User.objects.create_user(username=data['username'], password=data['password'],email=data['email'])
            u_id=newuser.id
            href="http://"+request.get_host()+"/pingtai/loginEmail/"+data['username']+".html"
            from django.core.mail import send_mail
            send_mail(
                '天涯社区博客平台',
                '恭喜注册成功，点击链接 %s 进行跳转'%(href),
                '1353052193@qq.com',
                [data['email']],
                fail_silently=False,
            )
            Info.objects.create(is_email=1,img="img/omikron.png",phone="",company="",
                                job="",science="",reason="",age=0,sex=0,isadv=0,u_id=u_id,type=1,salary=0)

            return render(request, "pingtai/zhuce.html", {'form': form})
        else:
            return render(request,"pingtai/zhuce.html",{'form':form})
    else:
        form=Zhuce()
        return render(request,"pingtai/zhuce.html",{'form':form})
def loginEmail(request,user):
    User.objects.filter(username=user).update(is_email=1)
    return redirect("/pingtai/")
import datetime
# 登录
# def login(request):
#     if request.method=='GET':
#         form=Login()
#         return render(request,'pingtai/login.html',{'form':form})
#     else:
#         form=Login(request.POST)
#         if form.is_valid():
#             import base64
#             # 登录
#             print("登录中")
#             data=form.cleaned_data
#             if request.user.is_authenticated:
#                 print("data",data)
#                 # 帐号和密码正确，cookie保存登录状态
#                 # 获取相应对象
#                 response=redirect(reverse('pingtai:index'))
#             else:
#                 response=redirect(reverse('pingtai:admin'))
#
#             name=json.dumps(data['name']) #解决cookie不能设置中文
#             response.set_cookie('name',name)
#             print("data['name']",data['name'])
#             return response
#         else:
#             # 失败，重新登录
#             return render(request, 'pingtai/login.html', {'form': form})
def islogin(request):
    if request.method=='GET':
        form=Login()
        print("get")
        return render(request,'pingtai/login.html',{'form':form})
    else:
        form = Login(request.POST)
        error_msg = ""
        if form.is_valid():
            form=Login(request.POST)
            print("登录啊")
            print("登录中")
            username = request.POST.get('username',None)
            password = request.POST.get('password',None)
            print(username,password)
            # request.user.is_authenticated:  验证是否用户是否登录，用来限制用户登录后才能执行的某些行为，必须搭配Django的登录与登出函数
            # authenticate() 提供了用户认证，即验证用户名以及密码是否正确,一般需要username  password两个关键字参数#,如果校验通过则返回User对象，如果校验不通过返回None
            user = authenticate(request,username=username, password=password)
            print(user)
            if user is not None:
                login(request,user)
                response= redirect(reverse('pingtai:index'))
                name = json.dumps(username)  # 解决cookie不能设置中文
                # response.set_cookie('name',name)
                return response
            else:
                error_msg = "用户名或者密码填写错误"
            return render(request, 'pingtai/login.html', {'form': form,'error_msg': error_msg})
        else:
            return render(request, 'pingtai/login.html', {'form': form,'error_msg': error_msg})



# def loginout(request):
#      print("退出登录")
# #      response = json.loads(request.COOKIES.get('name', None))
# #      response.delete_cookie("name")
# #      User.objects.filter(username=response).update(type=1)
# #      return redirect(reverse("pingtai:index"))
#
#      # print(2222)
#      # return response
from django.contrib.auth import logout
# 注销登录视图函数
def loginout(request):
    # 会将存储在用户session的数据全部清空，这样避免有人用当前用户的浏览器登陆然后就可以查看当前用户的数据了
    print("登出：",logout(request))
    return redirect(reverse('pingtai:islogin'))
@authuser
def person(request):
    if request.method == 'GET':
        name = ""
        if request.user.is_authenticated:
            name = request.user.username

        # type=User.objects.filter(username=name).first().info.type
        # print("类型",type)
        # queryset+字典
        person=User.objects.filter(username=name).values('username','email',).first()
        id=User.objects.filter(username=name).first().id
        try:
            info=Info.objects.filter(u_id=id).values('type','is_email','img','phone','company','job',
                                                     'real_name','reason','science','age','salary').first()
            img = User.objects.filter(username=name).first().info.img
        except:
            info=None
            img=None
        form=Upload()
        return render(request,"pingtai/person.html",{'person':person,'form':form,'info':info,'name':name,'img':img})
@authuser
def editperson(request):
    message = {'code': '', 'data': ''}
    if request.method == "POST":
        name = request.user.username
        kid = User.objects.filter(username=name).first().id
        real_name = request.POST.get('real_name', None)
        phone = request.POST.get('phone', None)
        company = request.POST.get('company', None)
        job = request.POST.get('job', None)
        reason = request.POST.get('reason', None)
        age = request.POST.get('age', None)
        salary = request.POST.get('salary', None)

myblog/blog/templates/pingtai/cate.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
  {% load static %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta name="renderer" content="webkit">
<title></title>
<link rel="stylesheet" href="{% static 'pingtai/css/pintuer.css' %}">
<link rel="stylesheet" href="{% static 'pingtai/css/admin.css' %}">
<script src="{% static 'pingtai/js/jquery.js' %}"></script>
<script src="{% static 'pingtai/js/pintuer.js' %}"></script>
</head>
<body>
<div class="panel admin-panel">
  <div class="panel-head"><strong class="icon-reorder"> 内容列表</strong></div>
  <div class="padding border-bottom">
    <button type="button" class="button border-yellow" onclick="window.location.href='#add'">
        <span class="icon-plus-square-o"></span> 添加分类</button>
  </div>
  <table class="table table-hover text-center">
    <tr>
      <th width="5%">序号</th>
      <th width="15%">一级分类</th>
      <th width="60%">关键字</th>
      <th width="20%">操作</th>
    </tr>
    {% for item in cate %}
    <tr id="c{{ item.id }}">
      <td>{{ forloop.counter }}</td>
      <td contenteditable="true" id="name{{ item.id }}" onblur="editCate({{ item.id }})">{{ item.name }}</td>
      <td>

        {% for obj in item.keyword_set.all %}
        <span id="k{{ obj.id }}"  style="border:1px solid red;padding:5px;margin:0 5px;cursor:pointer;box-sizing:border-box;" ondblclick="delkeyword({{ obj.id }})">
        {{ obj.name}}
          </span>
        {% endfor %}
      </td>
      <td><div class="button-group">
          <a class="button border-red" href="javascript:void(0)" onclick="return del({{ item.id }})"><span class="icon-trash-o"></span> 删除</a> </div></td>
    </tr>
    {% endfor %}
  </table>
</div>
<script type="text/javascript">
function del(id){
	$.ajax({
        url:"/pingtai/delCate/",
        type:"post",
        dataType:"json",
        data:{id:id},
        success:function(e){
            if(e['code']=="ok"){
                if(confirm("您确定要删除吗?")){
                    console.log(id)
                    $("#c"+id).detach()
                }
            }else{
                    alert("删除失败")
                  }
        }
    })
}
</script>
<div class="panel admin-panel margin-top">
  <div class="panel-head" id="add"><strong><span class="icon-pencil-square-o"></span>添加内容</strong></div>
  <div class="body-content">
    <form method="post" class="form-x" action="/pingtai/cate/">
      {% csrf_token %}
      <div class="form-group">
        <div class="label">
          <label>上级分类：</label>
        </div>
        <div class="field">
          <select name="type" class="input w50">
            <option value="0">请选择分类</option>
            {% for item in cate %}
            <option value="{{ item.id }}">{{ item.name }}</option>
            {% endfor %}
          </select>
          <div class="tips">不选择分类默认为添加分类</div>
        </div>
      </div>
      <div class="form-group">
        <div class="label">
          <label>单个添加：</label>
        </div>
        <div class="field">
          <input type="text" class="input w50" name="name" />
          <div class="tips"></div>
        </div>
      </div>
      <div class="form-group">
        <div class="label">
          <label>批量添加：</label>
        </div>
        <div class="field">
          <textarea type="text" class="input w50" name="tits" style="height:150px;" placeholder="多个分类标题请转行"></textarea>
          <div class="tips">多个分类或多个关键字以逗号","隔开</div>
        </div>
      </div>
      <div class="form-group">
        <div class="label">
          <label></label>
        </div>
        <div class="field">
          <button class="button bg-main icon-check-square-o" type="submit"> 提交</button>
        </div>
      </div>
    </form>
  </div>
</div>
<script>
  function delkeyword(id){
    $.ajax({
        url:"/pingtai/delkeyword/",
        type:"post",
        dataType:"json",
        data:{id:id},
        success:function(e){
            if(e['code']=="ok"){
                if(confirm("您确定要删除吗?")){
                     $("#k"+id).detach()
                }
            }else{
                alert("删除失败")
            }
        }
    })
  }
  <!--function editCate(id){-->
    <!--window.location.href='#add'-->
    <!--let tds=$(`#c${id}>td`)-->
    <!--$("[name=type] option").each(function(item,index){-->
        <!--if($(item).text()==tds[1].innerText){-->
            <!--$(item).attr("selected","selected")-->
        <!--}-->
    <!--})-->
    <!--$("[name=tits]").val(tds[2].innerText.replace(/\s+/g,"，"))-->
    <!--$(".form-x").attr("action","/updateCate")-->
  <!--}-->
  function editCate(id){
    $.ajax({
        url:"/pingtai/editCate/",
        type:"post",
        dataType:"json",
        data:{id:id,name:$("#name"+id).text()},
        success:function(e){
            if(confirm("您确定要修改吗?")){
                 alert("修改成功")
            }
        }
    })
  }
</script>
</body>
</html>

myblog/blog/templates/pingtai/info.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>注册信息</title>
    {% load static %}
    <link rel="stylesheet" href="{% static '/yuce/css/index.css' %}">
    <script src="{% static '/yuce/js/jquery.js' %}"></script>
    <script src="{% static '/yuce/js/index1.js' %}"></script>

</head>
<body>
    <!--背景图片-->
    <div class="fixed"></div>
    <main>
        <h2>注册用户</h2>
        <form action="/yuce/user/" method="post">
            {% csrf_token %}
            <div class="box">
                <label for="">请输入姓名：</label>
                {{ form.name }}
            </div>
            <div class="box">
             <label for="">请输入年龄：</label>
             {{ form.age }}
            </div>
            <div class="box">
                <label for="">请选择性别：</label>
                {{ form.sex }}
            </div>
            <div class="box">
                <label for="">请输入您的薪水：</label>
                {{ form.salary }}
            </div>
            <button id="button">注册</button>
        </form>

    </main>


</body>
</html>

myblog/blog/templates/pingtai/kaitong.html
{% extends 'self/muban.html'%}

{% block css%}
{% load static %}
<link rel="stylesheet" href="{% static '/pingtai/css/kaitong.css' %}">
{% endblock%}


{% block main %}
    <main>
        <div class="con">
            <h1>开通博客</h1>
            <div class="bottom">
                <div class="left" id="edit">
                    请填写信息
                </div>
            </div>
        </div>
        <form action="/kaitong/" method="post">
            {% csrf_token%}
            <div class="alert1">
                <div class="con con1">
                    {{ form.as_p }}
                <div class="button">
                    <span class="quxiao" style="background:#A79C87;margin-right:15px;cursor:pointer;">取消</span>
                    <button>提交</button>
                </div>
                </div>
            </div>


        </form>
    </main>
{% endblock %}

{% block js %}
<script src="{% static 'pingtai/js/index1.js' %}"></script>

{% endblock %}

myblog/blog/templates/pingtai/my.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>首页</title>
    {% load static %}
    <script src="{% static '/pingtai/js/jquery.js' %}"></script>
    <link rel="stylesheet" href="https://at.alicdn.com/t/font_850328_4weqx76q6s5.css">
    <link rel="stylesheet" href="{% static '/pingtai/css/my.css' %}">
</head>
<body>
<!--背景图片-->
    <div class="fixed"></div>
<!--菜单-->
    <ul class="meau">
        <li><a href="{% url 'pingtai:person' %}">个人资料</a></li>
        <li><a href="lianjie.html">发表博客</a></li>
        <li><a href="xiangqing.html">哈哈归档</a></li>
        <li><a href="liuyan.html">我的留言</a></li>
    </ul>
<!--搜索页面开始-->
    <div class="alert">
        <div class="search">Type then select or enter</div>
    </div>
<!--搜索页面结束-->
    <header>
        <div class="left">
            <i class="iconfont icon-sousuo"></i>
        </div>
        <div class="right" id="meau">
            <i class="iconfont icon-caidan"></i>
        </div>
    </header>
    <div class="head">
        <div class="center">
            <div class="top" style="background: url(/media/{{ img }}) no-repeat center;background-size: contain;"></div>
            <h3>{{ name }}</h3>
        </div>
    </div>
<!--顶部效果-->
    <div class="wrapper">
        <svg id="header-decor" class="decor bottom" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 100 100" preserveAspectRatio="none">
            <path class="large left" d="M0 0 L50 50 L0 100" fill="rgba(255,255,255, .1)"></path>
            <path class="large right" d="M100 0 L50 50 L100 100" fill="rgba(255,255,255, .1)"></path>
            <path class="medium left" d="M0 100 L50 50 L0 33.3" fill="rgba(255,255,255, .3)"></path>
            <path class="medium right" d="M100 100 L50 50 L100 33.3" fill="rgba(255,255,255, .3)"></path>
            <path class="small left" d="M0 100 L50 50 L0 66.6" fill="rgba(255,255,255, .5)"></path>
            <path class="small right" d="M100 100 L50 50 L100 66.6" fill="rgba(255,255,255, .5)"></path>
            <path d="M0 99.9 L50 49.9 L100 99.9 L0 99.9" fill="rgba(255,255,255, 1)"></path>
            <path d="M48 52 L50 49 L52 52 L48 52" fill="rgba(255,255,255, 1)"></path>
        </svg>
    </div>

<!--主要内容部分-->
    <main>
        <ul>
            <li class="small">
                <a href="xiangqing.html"><h1 class="tittle">交代是不可能交代的</h1>
                    <p>相隔上一次的更新我掰手指数一数，下意识的双腿一软，给各位小哥哥小姐姐们跪下了。自从有了对象后，周末几乎落下了主题的进度（邪魅的笑）。
                        一边开发新的主题，一边收集您们给我反馈回来的"臭虫"，还有新的主题后台看见了一些大神在...</p>
                </a>
            </li>
            <li class="big">
                <a href="xiangqing.html">
                    <div class="picbox"></div>
                    <div class="word">
                        <h1>我才不会写年终总结之瞎说篇</h1>
                        <h2>发布日期：2017-12-30</h2>
                        <h3>总浏览量：1203 reads</h3>
                    </div>
                    <p>确实讨厌去写所谓的年终总结，在公司已经被动的想领导上交一个总结，自己就懒得去总结，不然，我觉
                        得脑子里应该会编写出八九不离十的内容，所以正经八儿的事情略了，瞎说一下。 年初的人事调动是个人最不能接受的事情
                        ，但不接受也得接受，老板一句“这是命令...</p>
                    <div class="bottom">
                        <div class="left">READ MORE</div>
                        <div class="right">31 Comments</div>
                    </div>
                </a>
            </li>
            <li class="small">
                <a href="xiangqing.html"><h1 class="tittle">状态</h1>
                    <p>因为我这后半年飘忽不定的更新节奏，感觉真的对不住用户。
                        最近才松下来能处理反馈的bug，顺便加快新主题 Dcras 的制作，农历年后或许能上线，准确时间，不敢说-- 为了感谢大家对 Yarn 的支持
                        ，Dcras 会以 获兑现码半价的承诺 给 Yarn ...</p>
                </a>
            </li>
            <li class="big big2">
                <a href="xiangqing.html">
                    <div class="picbox"></div>
                    <div class="word">
                        <h1>重构图像样式测试</h1>
                        <h2>发布日期：2017-12-30</h2>
                        <h3>总浏览量：1203 reads</h3>
                    </div>
                    <p>如眼所见是一个图像样式，必须写五十左右的文字作为这个文本框的空白填充，不写也是可以的，强迫症不能容忍空白。</p>
                    <div class="bottom">
                        <div class="left">READ MORE</div>
                        <div class="right">31 Comments</div>
                    </div>
                </a>
            </li>
            <li class="big big1">
                <a href="xiangqing.html">
                    <div class="gray">
                        <div class="picbox"></div>
                        <div class="word">
                            <h1>给大家介绍一下</h1>
                            <h2>发布日期：2017-12-30</h2>
                            <h3>总浏览量：1203 reads</h3>
                        </div>
                        <p>现在的明星的影响力足以影响国内娱乐圈的"半壁江山"，发条微博，新浪都恐慌好几天，来来来，蹭个热点给大家介绍一下我的女朋友。</p>
                        <div class="bottom">
                            <div class="left">READ MORE</div>
                            <div class="right">31 Comments</div>
                        </div>
                    </div>
                </a>
            </li>
        </ul>
    </main>

<!--底部效果-->
    <div class="wrapper wrapper1">
        <svg id="header-decor" class="decor bottom" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 100 100" preserveAspectRatio="none">
            <path class="large left" d="M0 0 L50 50 L0 100" fill="rgba(255,255,255, .1)"></path>
            <path class="large right" d="M100 0 L50 50 L100 100" fill="rgba(255,255,255, .1)"></path>
            <path class="medium left" d="M0 100 L50 50 L0 33.3" fill="rgba(255,255,255, .3)"></path>
            <path class="medium right" d="M100 100 L50 50 L100 33.3" fill="rgba(255,255,255, .3)"></path>
            <path class="small left" d="M0 100 L50 50 L0 66.6" fill="rgba(255,255,255, .5)"></path>
            <path class="small right" d="M100 100 L50 50 L100 66.6" fill="rgba(255,255,255, .5)"></path>
            <path d="M0 99.9 L50 49.9 L100 99.9 L0 99.9" fill="rgba(255,255,255, 1)"></path>
            <path d="M48 52 L50 49 L52 52 L48 52" fill="rgba(255,255,255, 1)"></path>
        </svg>
    </div>

<footer>
    <ul class="top">
        <li>
            <i class="iconfont icon-weibo"></i>
        </li>
        <li>
            <i class="iconfont icon-ai-weixin"></i>
        </li>
        <li>
            <i class="iconfont icon-qq"></i>
        </li>
    </ul>
    <div class="bottom">Copyright©2018. Design by 17sucai</div>
</footer>
<script src="{% static 'pingtai/js/index1.js' %}"></script>
</body>
</html>